In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
import joblib

df = pd.read_csv ('dataset/clean_bot.csv')
df.replace({True: 1, False: 0}, inplace=True)
df.replace({'bot': 1, 'human': 0}, inplace=True)

X = df.iloc[:,:-1].values
y = df.iloc[:, -1].values
# scaler = StandardScaler()
# columns_to_standardize = ['favourites_count','followers_count','friends_count','average_tweets_per_day','account_age_days']
# df[columns_to_standardize] = scaler.fit_transform(df[columns_to_standardize])
# df

/tmp/ipykernel_8790/3387971672.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace({True: 1, False: 0}, inplace=True)
/tmp/ipykernel_8790/3387971672.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace({'bot': 1, 'human': 0}, inplace=True)


In [60]:
test_input = df.loc[[5]].values
test_input

array([[1.0000e+00, 0.0000e+00, 2.3700e+02, 2.7394e+04, 5.4200e+02,
        0.0000e+00, 0.0000e+00, 8.4280e+00, 1.3660e+03, 1.0000e+00]])

In [66]:
import numpy as np
input = np.array([[1.0000e+00, 0.0000e+00, 2.3700e+02, 2.7394e+04, 5.4200e+02,
        0.0000e+00, 0.0000e+00, 8.4280e+00, 1.3660e+03]])
input.shape

(1, 9)

In [67]:
X[5],

array([1.0000e+00, 0.0000e+00, 2.3700e+02, 2.7394e+04, 5.4200e+02,
       0.0000e+00, 0.0000e+00, 8.4280e+00, 1.3660e+03])

In [68]:
# test_input = X[5].reshape(1,-1)
test_input = input
test_input.shape

(1, 9)

In [69]:
scaler = joblib.load('models/scaler.pkl')
columns_to_standardize = [2,3,4,7,8]
data_to_transform = test_input[:,columns_to_standardize]
transformed_data = scaler.transform(data_to_transform)
standardized_input = test_input.copy()
standardized_input[:,columns_to_standardize] = transformed_data

standardized_input.shape

/home/stanley/miniconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


(1, 9)

In [70]:
loaded_model = joblib.load("models/logistic_regression_model.pkl")
predictions = loaded_model.predict_proba(standardized_input)
predictions

array([[0.33801169, 0.66198831]])

In [2]:
spam_test_input = {
    "features": ['default_profile', 'default_profile_image', 'favourites_count', 'followers_count','friends_count',	'geo_enabled','verified','average_tweets_per_day','account_age_days'],
    "regular": [1.000e+00, 0.000e+00, 8.433e+03, 5.170e+02, 6.330e+02, 1.000e+00,
        0.000e+00, 8.890e-01, 1.489e+03],
    "spam": [1.0000e+00, 0.0000e+00, 2.3700e+02, 2.7394e+04, 5.4200e+02,
        0.0000e+00, 0.0000e+00, 8.4280e+00, 1.3660e+03]
}

{'regular': array([1.000e+00, 0.000e+00, 8.433e+03, 5.170e+02, 6.330e+02, 1.000e+00,
        0.000e+00, 8.890e-01, 1.489e+03]),
 'spam': array([1.0000e+00, 0.0000e+00, 2.3700e+02, 2.7394e+04, 5.4200e+02,
        0.0000e+00, 0.0000e+00, 8.4280e+00, 1.3660e+03])}

### rows for

spam_account = 5
regular account = 3


In [75]:
input = np.array([1.0000e+00, 0.0000e+00, 2.3700e+02, 2.7394e+04, 5.4200e+02,
        0.0000e+00, 0.0000e+00, 8.4280e+00, 1.3660e+03])
input = np.array([input])
input.shape
data_to_transform = input[:,columns_to_standardize]
data_to_transform

array([[2.3700e+02, 2.7394e+04, 5.4200e+02, 8.4280e+00, 1.3660e+03]])

In [91]:
import joblib
import numpy as np

scaler = joblib.load('models/scaler.pkl')
model = joblib.load("models/logistic_regression_model.pkl")
columns_to_standardize = [2,3,4,7,8]
input = np.array([1.0000e+00, 0.0000e+00, 2.3700e+02, 2.7394e+04, 5.4200e+02,
        0.0000e+00, 0.0000e+00, 8.4280e+00, 1.3660e+03])

def spam_forward(input):
    input = np.array([input])
    data_to_transform = input[:,columns_to_standardize]    
    transformed_data = scaler.transform(data_to_transform)
    standardized_input = input.copy()
    standardized_input[:,columns_to_standardize] = transformed_data
    
    predictions = loaded_model.predict_proba(standardized_input)
    spam_pred = predictions[0][1]
    print(spam_pred)
    
spam_forward(input)

0.6619883051429746


/home/stanley/miniconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
